<a href="https://colab.research.google.com/github/HUGOBROWNING/Machine-learning-from-scratch/blob/main/Random_Forest.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import seaborn as sns
import pandas as pd
sns.get_dataset_names()

['anagrams',
 'anscombe',
 'attention',
 'brain_networks',
 'car_crashes',
 'diamonds',
 'dots',
 'dowjones',
 'exercise',
 'flights',
 'fmri',
 'geyser',
 'glue',
 'healthexp',
 'iris',
 'mpg',
 'penguins',
 'planets',
 'seaice',
 'taxis',
 'tips',
 'titanic']

In [2]:
data = sns.load_dataset('healthexp')
data.head(10)

Year        Country  Spending_USD  Life_Expectancy
0  1970        Germany       252.311             70.6
1  1970         France       192.143             72.2
2  1970  Great Britain       123.993             71.9
3  1970          Japan       150.437             72.0
4  1970            USA       326.961             70.9
5  1971         Canada       313.391             72.8
6  1971        Germany       298.251             70.8
7  1971  Great Britain       134.172             71.9
8  1971          Japan       163.854             72.9
9  1971            USA       357.988             71.2

In [4]:
data = pd.get_dummies(data)
data.head(3)

Year  Spending_USD  Life_Expectancy  Country_Canada  Country_France  \
0  1970       252.311             70.6           False           False   
1  1970       192.143             72.2           False            True   
2  1970       123.993             71.9           False           False   

   Country_Germany  Country_Great Britain  Country_Japan  Country_USA  
0             True                  False          False        False  
1            False                  False          False        False  
2            False                   True          False        False

In [6]:
X = data.drop(columns = ['Life_Expectancy'], axis = 1)
y = data['Life_Expectancy']
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state=42)
from sklearn.ensemble import RandomForestRegressor
model = RandomForestRegressor(random_state=13)
model = model.fit(X_train, y_train)
y_pred = model.predict(X_test)
y_pred

array([72.864, 81.395, 82.419, 76.887, 80.997, 81.743, 81.218, 78.279,
       78.703, 81.777, 76.609, 78.742, 81.532, 80.612, 78.544, 80.373,
       80.158, 74.336, 76.781, 78.718, 73.749, 75.022, 79.898, 83.475,
       84.233, 81.076, 76.611, 73.908, 71.308, 77.55 , 72.872, 75.722,
       72.579, 77.678, 77.773, 75.376, 81.015, 78.757, 71.323, 75.05 ,
       76.256, 77.808, 74.979, 74.14 , 77.708, 81.417, 72.443, 80.108,
       78.187, 81.917, 75.558, 80.761, 78.248, 71.646, 79.371])

In [7]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np
mean_squared_error(y_test, y_pred), np.sqrt(mean_squared_error(y_test, y_pred)), mean_absolute_error(y_test, y_pred), r2_score(y_test, y_pred)

(0.12957590909089994, 0.3599665388489602, 0.27990909090908, 0.9893864896823702)

In [11]:
param_grid = {
    'n_estimators': [100, 200, 300],
    'max_depth': [10, 20, 30],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4]
}
from sklearn.model_selection import GridSearchCV
model_cv = GridSearchCV(estimator = model, param_grid=param_grid, cv = 3, scoring = 'neg_mean_squared_error')
model_cv = model_cv.fit(X_train, y_train)
y_pred = model_cv.predict(X_test)
y_pred

array([72.87733333, 81.42233333, 82.44766667, 76.921     , 81.033     ,
       81.75033333, 81.22333333, 78.279     , 78.69633333, 81.818     ,
       76.585     , 78.72433333, 81.551     , 80.66633333, 78.554     ,
       80.41866667, 80.19333333, 74.40833333, 76.74633333, 78.72133333,
       73.77733333, 75.02933333, 79.93933333, 83.53233333, 84.21233333,
       81.07766667, 76.57166667, 73.93466667, 71.345     , 77.565     ,
       72.86533333, 75.74833333, 72.56233333, 77.68466667, 77.838     ,
       75.41933333, 81.01866667, 78.755     , 71.208     , 75.03833333,
       76.31066667, 77.814     , 74.92533333, 74.19266667, 77.68266667,
       81.37666667, 72.414     , 80.088     , 78.25      , 81.916     ,
       75.54466667, 80.80333333, 78.29933333, 71.69666667, 79.43366667])

In [16]:
import pandas as pd
path = '/content/500hits.csv'
data = pd.read_csv(path, encoding = 'latin-1')
data.head(6)

PLAYER  YRS     G     AB     R     H   2B   3B   HR   RBI    BB  \
0           Ty Cobb   24  3035  11434  2246  4189  724  295  117   726  1249   
1       Stan Musial   22  3026  10972  1949  3630  725  177  475  1951  1599   
2      Tris Speaker   22  2789  10195  1882  3514  792  222  117   724  1381   
3       Derek Jeter   20  2747  11195  1923  3465  544   66  260  1311  1082   
4      Honus Wagner   21  2792  10430  1736  3430  640  252  101     0   963   
5  Carl Yastrzemski   23  3308  11988  1816  3419  646   59  452  1844  1845   

     SO   SB   CS     BA  HOF  
0   357  892  178  0.366    1  
1   696   78   31  0.331    1  
2   220  432  129  0.345    1  
3  1840  358   97  0.310    1  
4   327  722   15  0.329    1  
5  1393  168  116  0.285    1

In [17]:
data = data.drop(columns= ['PLAYER', 'CS'],  axis = 1)
data.head(2)

YRS     G     AB     R     H   2B   3B   HR   RBI    BB   SO   SB     BA  \
0   24  3035  11434  2246  4189  724  295  117   726  1249  357  892  0.366   
1   22  3026  10972  1949  3630  725  177  475  1951  1599  696   78  0.331   

   HOF  
0    1  
1    1

In [23]:
X = data.drop(columns = ['HOF'], axis = 1)
y = data['HOF']

In [26]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state=42)
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier()
model = model.fit(X_train, y_train)
y_pred = model.predict(X_test)
y_pred

array([1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 1, 0])

In [30]:
from sklearn.metrics import mean_squared_error, r2_score
r2_score(y_test, y_pred), mean_squared_error(y_test, y_pred)

(0.4193548387096775, 0.12903225806451613)

In [33]:
import numpy as np
sum_res = np.sum((y_test - y_pred)**2)
mean = np.mean(y_test)
sum_tot = np.sum((y_test - mean)**2)
r2 = 1 - (sum_res / sum_tot)
r2

0.4193548387096775

In [34]:
model.score(X_test, y_test)

0.8709677419354839

In [35]:
from sklearn.metrics import classification_report, accuracy_score
accuracy_score(y_test, y_pred)

0.8709677419354839

In [36]:
classification_report(y_test, y_pred)

'              precision    recall  f1-score   support\n\n           0       0.88      0.94      0.91        62\n           1       0.85      0.74      0.79        31\n\n    accuracy                           0.87        93\n   macro avg       0.87      0.84      0.85        93\nweighted avg       0.87      0.87      0.87        93\n'